language: java
install: true
jdk: oraclejdk8
env:
  matrix:
  - TERM=dumb
before_script:
  - ./gradlew --version
script: ./gradlew --no-daemon build --stacktrace
after_success:
  - ./gradlew --no-daemon jacocoTestReport coveralls